/**
 * The built-in rules.
 *
 * Imported statically rather than discovered on disk, so that the compiled
 * package is self-contained and every rule is type-checked.
 *
 * This file is generated by `npm run generate:rules`; add a rule module to
 * src/rules and run that rather than editing this list.
 */
import type {LintRule} from '../types.ts';
import allowedTags from './allowed-tags.ts';
import backgroundSetupOnly from './background-setup-only.ts';
import fileName from './file-name.ts';
import indentation from './indentation.ts';
import keywordsInLogicalOrder from './keywords-in-logical-order.ts';
import maxScenariosPerFile from './max-scenarios-per-file.ts';
import nameLength from './name-length.ts';
import newLineAtEof from './new-line-at-eof.ts';
import noBackgroundOnlyScenario from './no-background-only-scenario.ts';
import noDupeFeatureNames from './no-dupe-feature-names.ts';
import noDupeFileNames from './no-dupe-file-names.ts';
import noDupeScenarioNames from './no-dupe-scenario-names.ts';
import noDuplicateTags from './no-duplicate-tags.ts';
import noEmptyBackground from './no-empty-background.ts';
import noEmptyFile from './no-empty-file.ts';
import noExamplesInScenarios from './no-examples-in-scenarios.ts';
import noFilesWithoutScenarios from './no-files-without-scenarios.ts';
import noHomogenousTags from './no-homogenous-tags.ts';
import noMultipleEmptyLines from './no-multiple-empty-lines.ts';
import noPartiallyCommentedTagLines from './no-partially-commented-tag-lines.ts';
import noRestrictedPatterns from './no-restricted-patterns.ts';
import noRestrictedTags from './no-restricted-tags.ts';
import noScenarioOutlinesWithoutExamples from './no-scenario-outlines-without-examples.ts';
import noScenariosWithoutThen from './no-scenarios-without-then.ts';
import noScenariosWithoutWhen from './no-scenarios-without-when.ts';
import noSuperfluousTags from './no-superfluous-tags.ts';
import noTrailingSpaces from './no-trailing-spaces.ts';
import noUndeclaredVariables from './no-undeclared-variables.ts';
import noUnnamedFeatures from './no-unnamed-features.ts';
import noUnnamedScenarios from './no-unnamed-scenarios.ts';
import noUnusedVariables from './no-unused-variables.ts';
import oneSpaceBetweenTags from './one-space-between-tags.ts';
import onlyOneWhen from './only-one-when.ts';
import requiredTags from './required-tags.ts';
import scenarioSize from './scenario-size.ts';
import useAnd from './use-and.ts';

/** Every rule shipped with gurkencheck, in alphabetical order. */
export const BUILT_IN_RULES: readonly LintRule[] = [
  allowedTags,
  backgroundSetupOnly,
  fileName,
  indentation,
  keywordsInLogicalOrder,
  maxScenariosPerFile,
  nameLength,
  newLineAtEof,
  noBackgroundOnlyScenario,
  noDupeFeatureNames,
  noDupeFileNames,
  noDupeScenarioNames,
  noDuplicateTags,
  noEmptyBackground,
  noEmptyFile,
  noExamplesInScenarios,
  noFilesWithoutScenarios,
  noHomogenousTags,
  noMultipleEmptyLines,
  noPartiallyCommentedTagLines,
  noRestrictedPatterns,
  noRestrictedTags,
  noScenarioOutlinesWithoutExamples,
  noScenariosWithoutThen,
  noScenariosWithoutWhen,
  noSuperfluousTags,
  noTrailingSpaces,
  noUndeclaredVariables,
  noUnnamedFeatures,
  noUnnamedScenarios,
  noUnusedVariables,
  oneSpaceBetweenTags,
  onlyOneWhen,
  requiredTags,
  scenarioSize,
  useAnd,
];
