/**
 * Regenerates `src/rules/index.ts` from the rule modules on disk.
 *
 * The registry is a plain list of static imports rather than a directory scan
 * so that the published package is self-contained and every rule is
 * type-checked. Run `npm run generate:rules` after adding a rule file.
 */
import fs from 'node:fs';
import path from 'node:path';

const RULES_DIR = 'src/rules';
const REGISTRY = path.join(RULES_DIR, 'index.ts');

/** `no-empty-file` -> `noEmptyFile` */
function toIdentifier(ruleName: string): string {
  return ruleName.replace(/-(\w)/g, (_match, letter: string) => letter.toUpperCase());
}

/** Every rule module in `src/rules`, by name, in alphabetical order. */
export function findRuleNames(directory: string = RULES_DIR): string[] {
  return fs
    .readdirSync(directory)
    .filter((file) => file.endsWith('.ts') && file !== 'index.ts')
    .map((file) => path.basename(file, '.ts'))
    .sort();
}

/** The contents `src/rules/index.ts` should have. */
export function renderRegistry(ruleNames: readonly string[]): string {
  const imports = ruleNames
    .map((name) => `import ${toIdentifier(name)} from './${name}.ts';`)
    .join('\n');
  const entries = ruleNames.map((name) => `  ${toIdentifier(name)},`).join('\n');

  return `/**
 * The built-in rules.
 *
 * Imported statically rather than discovered on disk, so that the compiled
 * package is self-contained and every rule is type-checked.
 *
 * This file is generated by \`npm run generate:rules\`; add a rule module to
 * src/rules and run that rather than editing this list.
 */
import type {LintRule} from '../types.ts';
${imports}

/** Every rule shipped with gurkencheck, in alphabetical order. */
export const BUILT_IN_RULES: readonly LintRule[] = [
${entries}
];
`;
}

if (import.meta.filename === process.argv[1]) {
  const names = findRuleNames();
  fs.writeFileSync(REGISTRY, renderRegistry(names));
  console.log(`Wrote ${REGISTRY} with ${names.length} rules`);
}
